### ISSUE TITLE
Write a searcher class to fetch EDS results

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-bento-app#1]
We could use the ebsco-eds gem as part of the searcher (which would make a useful gem for anybody else using both EBSCO and our chosen bento framework).

However; we could also use the SearchWorks json endpoint which might greatly reduce the scope and complexity for completing this (given that we'll most likely want to have something similar for catalog results anyway).

One consideration here would be how guest vs. non-guest will work from the bento app.  If we're using a ruby class to issue the search to the Blacklight API, then the request's IP address will be that of the bento application itself and not the user.

**Comment by drh-stanford** [comment]
I think this makes a lot of sense. There's no jbuilder view current for articles so the default `format=json` is outputing the raw EDS field names, etc.

For the guest vs. non-guest, we could implement an `opensearch` controller endpoint and always use guest mode for it. I think we get that method for "free" in `Blacklight::Catalog`

**Comment by drh-stanford** [comment]
Just a simple test that adding the route `get '/article/opensearch' => 'article#opensearch'` yields the search with titles without any modifications/overrides.

### query for engine with JSON response

![screen shot 2017-08-02 at 2 18 50 pm](https://user-images.githubusercontent.com/1861171/28895530-8ff50f1e-778d-11e7-981a-afb359bcf346.png)

**Comment by drh-stanford** [comment]
We get the built-in support for RSS and ATOM on the `index` endpoint -- though it's not working on article search by default (exception: `undefined method 'show_solr_document_url'`). Either of those formats would provide more structure, at least title/description/link.

**Comment by jkeck** [comment]
@drh-stanford I don't believe they have a representation of the facet response though, do they?

**Comment by drh-stanford** [comment]
No, the "channel" details are slim in those formats. 

I didn't realize that we need facet values in the response. The built-in Blacklight JSON support sounds like the way to go for that.

Maybe it's just a matter of implementing a different controller method that would either always use guest mode, or use a proxy header (`X-Forwarded-For`) for the IP address validation. Rails' `request.remote_ip` already checks for those headers (see https://apidock.com/rails/ActionDispatch/RemoteIp and https://github.com/sul-dlss/SearchWorks/blob/article-search/app/controllers/article_controller.rb#L210). We could also check that the IP address matched the Bento box servers to protect against spoofing.

**Comment by jkeck** [comment]
👍 there is already some IP spoofing protection in rails, which we'll need to make sure we don't accidentally trigger.

**Comment by drh-stanford** [comment]
@jkeck I have the start of a branch going here: https://github.com/sul-dlss/sul-bento-app/compare/1-eds-search

It implements an `ArticleSearchService` class, that you can call like so:

```
response = ArticleSearchService.new.search('my query')
response.results # Array of Hash with :title, :description, :url for each hit
response.facets # Array of Solr Hash for facets
response.body # raw JSON
```

One thing it doesn't have is a way to select which facet fields you want back in the query. I haven't figured out how/whether the JSON API supports that.

You need a `config/settings.local.yml` that looks like so:

```yml
EDS_QUERY_URL: 'http://localhost:3000/article?q=%{q}&rows=%{max}&format=json'
EDS_FETCH_URL: 'http://localhost:3000/article/%{id}'
```

**Comment by drh-stanford** [comment]
I added a demo controller that you can use to drive the engine -- `http://localhost:3001/demo/article_search?q=cats` for example. But the theming is screwed up -- the background and foreground colors are blue

**Comment by jkeck** [comment]
Closing this as the leftover tasks (facets) is ticketed in a separate issue.
