### ISSUE TITLE
[sul-bento-app/prod] AbstractSearchService::NoResults: AbstractSearchService::NoResults

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#101]
## Backtrace

    line 127 of [PROJECT_ROOT]/app/services/abstract_search_service.rb: search
    line 6 of [PROJECT_ROOT]/app/searchers/quick_search/article_searcher.rb: search

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53517/faults/34768283)

**Comment by camillevilla** [comment]
Example search: 
- [prod](https://library.stanford.edu/all/?utf8=%E2%9C%93&q=marriage+law)
- [localhost](http://localhost:3000/all/?utf8=%E2%9C%93&q=marriage+law) 

`searcher.results` throws the error `NoMethodError Exception: undefined method `text' for nil:NilClass` in [_module.html.erb](https://github.com/sul-dlss/sul-bento-app/blob/e4a4d5b21fdf15da6a0657b79ee7512e8dea86ad/app/views/quick_search/search/_module.html.erb#L11)

**Comment by drh-stanford** [comment]
I'm not able to reproduce this in production. Perhaps the library website server was being flakey? The NoResults exception happens when there's a connection issue to the library website server. Maybe we should handle the exception?
