### ISSUE TITLE
Review and approve Chapter Three work on SOLR JSON API

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-bento-app#105]
Need to have @drh-stanford review work done by Chapter Three on the solr JSON API.  Either approve for them to deploy to production or give feedback for improvements.  

This is not a ticket to implement the Library Web in SUL-BENTO, just work to review the Chapter Three API.

**Comment by drh-stanford** [comment]
I found a couple issues with the JSON API and I commented on them in the Chapter 3 ticket system (see https://chapterthree.teamworkpm.net/#/tasks/6679134). Waiting for a response now.

**Comment by drh-stanford** [comment]
This is working in stage now -- an example:

  https://library-stage.stanford.edu/bento?keys=chinese%20art&n=3

**Comment by camillevilla** [comment]
^-- note that VPN is required

**Comment by camillevilla** [comment]
@snydman @drh-stanford and I agreed that this API looks ok to ship to production. Some work needs to be done on the Bento end to utilize this API. We should discuss whether it makes sense to deploy to production now or wait until the next SearchWorks work cycle.

**Comment by camillevilla** [comment]
This is not currently in stage. We'll need to ask Brian from Chapter 3 to deploy this when we're ready to review.

**Comment by camillevilla** [comment]
Currently waiting Chapter Three to deploy this to stage. We have some PHP upgrades that are holding up the deployment queue.

**Comment by camillevilla** [comment]
Chapter Three has redeployed this to library-stage:
https://library-stage.stanford.edu/bento?keys=chinese%20art&n=3

**Comment by mejackreed** [comment]
I'm noticing that this API contains BOF characters at the beginning of the response. This is invalid JSON. Is there anyway to report this upstream?

**Comment by mejackreed** [comment]
Issues with Chapter 3 JSON API for library website:
1. JSON API contains leading byte order mark (BOM) characters. Per JSON spec, this is invalid: https://tools.ietf.org/html/rfc7159#section-8.1 . We can work around this, but should be changed.

2. Facet hit counts contain different information from library website. Compare facet hits for "Blog"

Name | JSON API Count | Website count 
---|---|---
Blog | 32 | 339

https://library-stage.stanford.edu/bento?keys=chinese%20art&n=3
https://library-stage.stanford.edu/search/website?search=chinese%20art

Its unclear to me if this is due to differing data in environments or a problem with the API counts.

3. Relevancy changes. I'm not sure if this is intended, but The same items appear differently.

![image](https://user-images.githubusercontent.com/1656824/89338695-2e469600-d65a-11ea-91ee-2374052e20d6.png)

**Comment by sleepingmonk** [comment]
Hi!

I'll see if I can track down the BOM issue. 

As for the rest of it, looking at the implementation, the API output is hand coded in a custom Drupal module. While the on site search results come from a Drupal view. This was all built by someone long before I came to the project.  I only enabled it and deployed it to the test environments. I don't know the original discussion or thinking about this feature, but I can look into it. It should be relatively straightforward to create a JSON display of the same view that powers the search page.

**Comment by sleepingmonk** [comment]
BOM issue resolved.  There was a BOM on an unrelated module file causing it to be rendered on all output from the site.  Tracked it down, removed it and deployed to stage.

I did not create a Drupal Views display for the JSON out put. Upon catching up on this thread it seems the custom module is the most direct way to get the results asked for on the task thread.  I have few notes on it's use though:

- Both the view and the module are using the same solr index. https://sul-solr.stanford.edu:443/solr/sul-cms-prod
- The API parameter `n` sets the number of results and defaults to `3`.  Increase that number to get more results.
- The parameter `keys` and the search terms on the site use an "OR" condition, so Chinese Art will return results for Chinese OR Art.  Try "Chinese Art" or `keys=%22chinese%20art%22` to search for the more specific term. This will show smaller counts for "Blog" facet, for example.
- The description pulls the same summary/description as the Drupal view but it's not trimmed. That's up to the consumer application. 
- The API is actually showing more results for the same terms.  If I up the `n` to 100 I get 75 results where the site returns only 12.  I still need to look at that.
