### ISSUE TITLE
Query strings are not translating ampersands

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#111]
See JIRA ticket

Query: Sun & steel

## SearchWorks
Catalog:  https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=Sun+%26+steel
Article: https://searchworks.stanford.edu/articles?q=Sun+%26+steel&search_field=search

## QuickSearch
https://library.stanford.edu/all/?utf8=%E2%9C%93&q=Sun+%26+steel
Catalog link: https://searchworks.stanford.edu/?q=Sun%20&%20steel
Articles link: https://searchworks.stanford.edu/articles?q=Sun%20&%20steel&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text

**Comment by ahafele** [comment]
https://jirasul.stanford.edu/jira/browse/VUF-6360
