### ISSUE TITLE
Potential for adding an EarthWorks search?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-bento-app#114]
@mapninja mentioned that it would be nice to have EarthWorks added to the bento. Adding this issue here to track that discussion.

**Comment by mapninja** [comment]
Just adding 2 cents. THis will be particularly desirable when we have the scanned maps all ingested in EW.

**Comment by jkeck** [comment]
👍 It would also be good to call out what facet we should use for the `Results Included` section:

<img width="1157" alt="results-include" src="https://user-images.githubusercontent.com/96776/35418661-873a4034-01e8-11e8-8fd1-a361fe20ad7b.png">

As well as what the "description" should be (e.g. "Books, media, physical & digital resources" text in catalog bento)

**Comment by mejackreed** [comment]
My initial thought is our "format" facet `dc_format_s` to be used for the "results included" section. 

Another question, would we want to include results from only Stanford or from other institutions too?

**Comment by mapninja** [comment]
Ooh, good question on the Stanford only vs All Institutions. My initial impulse would be to show Stanford holdings, or maybe Stanford + Public and available?
