### ISSUE TITLE
Add a Yewno embed

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-bento-app#14]
This is similar to what's already on the library bento page (possibly small JS drop-in?)

**Comment by mejackreed** [comment]
https://github.com/sul-dlss/sulweb/search?utf8=%E2%9C%93&q=yewno&type=

**Comment by mejackreed** [comment]
Developer Documentation: https://about.yewno.com/wp-content/uploads/2017/08/Yewno-Discover-Widget-Integration-Guide-4.pdf
