### ISSUE TITLE
Bento html updates [WIP]

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-bento-app#191]
### App

- [x] Add page title `<title>Search : Stanford Libraries</title>`
- [x] Change `<meta name="viewport" content="width=device-width">` to `<meta name="viewport" content="width=device-width,initial-scale=1.0">` to solve a width issue on mobile. 

### Home page
- [x] add `alt=""` to 5 home page images `<div class="card"><img>`
- [x] add `<h1>` around the search label 
- [x] change `<h3>` and `<h4>` on home page to `<h2>` (so home page is consistent with results page)
- [x] change `.homepage h3` to `.homepage h2` in `homepage.scss`

**Comment by cbeer** [comment]
For the `<title`>, is `Search | Stanford Libraries` acceptable (or, with a search query, `(some truncated query) | Search | Stanford Libraries`?

**Comment by jvine** [comment]
Is the bar better than colon? We use colon in SearchWorks, was just following that pattern, but not that concerned about it. Adding query is great.

**Comment by cbeer** [comment]
Great; the bar is what upstream is giving us.

**Comment by mejackreed** [comment]
Resolved now with #200 and #199
