### ISSUE TITLE
Update Yewno URL to use proxy on results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-bento-app#194]
The homepage link to Yewno uses `https://stanford.idm.oclc.org/login?url=https://discover.yewno.com`, but the results page goes directly to `https://discover.yewno.com/?query=` which doesn't work from off campus.

**Comment by camillevilla** [comment]
@jvine It looks like this link is actually provided to us by Yewno. We add a little CSS to restyle the link and change the link text. I can send some feedback to Yewno. I needed to get in touch with them anyway... it looks like their widget documentation has moved.

**Comment by camillevilla** [comment]
Aaaand @cbeer is on it with a local fix in #328

**Comment by cbeer** [comment]
Can't tell you where the docs are, but [ND fixed it](https://github.com/ndlib/yewno/blob/master/index.html#L13) like that 🤷‍♂️
