### ISSUE TITLE
Add dejavu font to result titles

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#26]
Dejavu needs to be imported and added to the stylesheets. In SearchWorks, we use Dejavu for record titles because it handles diacritics etc. better than Source Sans Pro.

**Comment by drh-stanford** [comment]
@jvine does this look ok? or is the Dejavu font intended to be only used for record titles in the Bento? does this affect the homepage at all (e.g., Bento panels)?

### Before
![screen shot 2017-09-19 at 2 15 19 pm](https://user-images.githubusercontent.com/1861171/30615823-0285dda6-9d45-11e7-84c3-5e608495cac9.png)

### After
![screen shot 2017-09-19 at 2 15 09 pm](https://user-images.githubusercontent.com/1861171/30615833-05cdf764-9d45-11e7-9c37-4d6685159bd7.png)

**Comment by jvine** [comment]
@drh it should be for record titles only, please. (It's only to handle diacritics.)

Sent from my iPhone

On Sep 19, 2017, at 2:18 PM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jvine<https://github.com/jvine> does this look ok? or is the Dejavu font intended to be only used for record titles in the Bento? does this affect the homepage at all (e.g., Bento panels)?

Before

[screen shot 2017-09-19 at 2 15 19 pm]<https://user-images.githubusercontent.com/1861171/30615823-0285dda6-9d45-11e7-84c3-5e608495cac9.png>

After

[screen shot 2017-09-19 at 2 15 09 pm]<https://user-images.githubusercontent.com/1861171/30615833-05cdf764-9d45-11e7-9c37-4d6685159bd7.png>

**Comment by drh-stanford** [comment]
ok thanks. here's what the record titles only looks like:

### Before
![screen shot 2017-09-19 at 2 47 24 pm](https://user-images.githubusercontent.com/1861171/30617105-7dc48ac2-9d49-11e7-8611-c268235185d2.png)

### After
![screen shot 2017-09-19 at 2 46 58 pm](https://user-images.githubusercontent.com/1861171/30617106-7f53ab84-9d49-11e7-9072-beabf14cc1ef.png)

**Comment by jvine** [comment]
+1

Sent from my iPhone

On Sep 19, 2017, at 2:48 PM, Darren Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


ok thanks. here's what the record titles only looks like:

Before

[screen shot 2017-09-19 at 2 47 24 pm]<https://user-images.githubusercontent.com/1861171/30617105-7dc48ac2-9d49-11e7-8611-c268235185d2.png>

After

[screen shot 2017-09-19 at 2 46 58 pm]<https://user-images.githubusercontent.com/1861171/30617106-7f53ab84-9d49-11e7-9072-beabf14cc1ef.png>
