### ISSUE TITLE
Heading structure

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#286]
`<h3 class="result-set-subheading">`  should not be a heading at all. `<span>` is ok (but will need to be styled to match margins)

Better structure would be to include the `<span>` inside the `<h2>`

`<h2 class="result-set-heading">
      Catalog <span class="result-set-subheading">
  Books, media, physical &amp; digital resources
</span>
    </h2>`

with adjustments to the layout to improve wrapping, especially at narrow block widths.

**Comment by cbeer** [comment]
@jvine it looks like we're doing some special things with the mobile design. If the `result-set-subheading` is pulled into the h2, I think we'll lose some of that.

**Comment by jvine** [comment]
Okay. We can keep the current order and just change the `<h3>` to a `<span>`. 

I will experiment with adding `aria-describedby` to the `<h2>`.
