### ISSUE TITLE
“Found results in” & “Results include” structure

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#289]
“Found results in” (summary at the top) has a `<dt>` and `<dd>` with no parent `<dl>`
Design change in A.2 fixes this

~“Results include” has a combination of `<span>` and `aria-labelledby` that isn’t actually functional.~
~Convert these to `<dl>` structures with no aria.~

**Comment by cbeer** [comment]
I've pulled the Results include stuff  over to #292.

**Comment by jkeck** [comment]
I'll do the "Found results in" while tackling #296
