### ISSUE TITLE
Metadata improvements for Catalog block

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#293]
Desired updates:
- Add author (not linked)
- Add imprint
- Improve 2-line truncation for descriptions
- Add online link (Might need to split off to a different ticket??)

## Before
![Screen Shot 2020-07-28 at 11 27 14 PM](https://user-images.githubusercontent.com/5402927/88764524-f4d9cc00-d129-11ea-8d1e-f1edc34f8099.png)
![Screen Shot 2020-07-28 at 11 31 15 PM](https://user-images.githubusercontent.com/5402927/88764858-81848a00-d12a-11ea-862c-d6348e670641.png)
![Screen Shot 2020-07-28 at 11 32 43 PM](https://user-images.githubusercontent.com/5402927/88764971-abd64780-d12a-11ea-871b-5d54ed890113.png)

## After
![metdata updates](https://user-images.githubusercontent.com/5402927/88764254-77ae5700-d129-11ea-9003-053ba13d8b12.png)

## Sample records
- [White matter in cognitive neuroscience](https://searchworks.stanford.edu/view/6335708)
- [Foundations in social neuroscience](https://searchworks.stanford.edu/view/12895340)
- [Culture, curriculum, and identity in education](https://searchworks.stanford.edu/view/8632837)

**Comment by jkeck** [comment]
Should we also provide the temporary access links?  I haven't done that currently, but would be happy to add a ticket to work on that separately from this if so.

**Comment by camillevilla** [comment]
Ack, good point, @jkeck. I think the answer here is yes, but want to confirm with @jvine.
