### ISSUE TITLE
Add LibGuides block to bento home page

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#297]
Depends on #295
![revised-homepage](https://user-images.githubusercontent.com/5402927/88835043-8e849600-d189-11ea-958d-98504794e886.png)
![guides-home-page-block](https://user-images.githubusercontent.com/5402927/88835050-8fb5c300-d189-11ea-86bd-8efeae52465b.png)

This should probably be accompanied by a responsive design check ✅ (might depend on whether this is the 5th or 6th block implemented)

**Comment by jkeck** [comment]
@jvine / @camillevilla  Is there a source for the new nerd squirrel image?

**Comment by jvine** [comment]
<img width="557" alt="nerdsquirrel" src="https://user-images.githubusercontent.com/6945691/89324264-def16d00-d63b-11ea-80da-0cc1d7b98282.png">
