### ISSUE TITLE
Update the banner, and complete the all-catalog-articles passed-search loop

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-bento-app#308]
Goals are to separate Bento from its close association with the website using our generic application branding, and complete the SearchWorks all/catalog/articles loop.

<img width="1210" alt="bento new banner" src="https://user-images.githubusercontent.com/6945691/89079615-ba477d80-d33b-11ea-87ea-5ed5dae3b1d9.png">

1. Move the SUL logo up to the top left, and link it to library.stanford.edu
2. Add a text `<h1>` to the red banner: "Search all"
   - add the drop-down behaviour of SearchWorks to the "all"
3. Move the search box to the red banner
4. Edit the text that's currently below the search box, left align it, and style it as `.h2` (but it's not a heading)

When the user clicks the "all" dropdown, the popup menu appears and the user can select Catalog or Articles+. If there is an active search in Bento, the same search is sent to the new context.

<img width="1210" alt="bento new banner with dropdown" src="https://user-images.githubusercontent.com/6945691/89079707-ec58df80-d33b-11ea-9632-684ebbd1fd24.png">

**Comment by cbeer** [comment]
@jvine for the search button -- how do you want to style the hover/focus?

**Comment by jvine** [comment]
Apologies - this was me being lazy because of in-browser design and introducing a new pattern. If it's not too late, using the same styling as SearchWorks would be better.

**Comment by cbeer** [comment]
👍 right answer!
