### ISSUE TITLE
Forward user IP through requests to SearchWorks

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-bento-app#32]
Currently the IP address of the bento app is what is executing the request which means that it will always get non-guest mode results.

**Comment by mejackreed** [comment]
Looking into this, I wanted to report my results here:

QuickSearch has the logic of "on campus" that is handled by a regex https://github.com/sul-dlss/sul-bento-app/blob/master/config/quick_search_config.yml#L36

That allows you to pass in a `Boolean` of `on_campus?` to a custom searcher. We could then in our `AbstractSearchService` pass a "good" ip or a bad one in the `X-Forwarded-For` header based on the on campus status. 

What do people think about this approach? The alternative is overwriting https://github.com/NCSU-Libraries/quick_search/blob/master/app/controllers/quick_search/search_controller.rb#L41-L114 which feels like a bad idea.

**Comment by jkeck** [comment]
I would be 👌 w/ that approach generally.

Just wondering though if we might want to (initially) force guest mode all the time.  We talked about this in a meeting some number of weeks ago and I believe were willing to launch with only being in guest mode from the bento (I worry the regex approach for campus IP won't be as cut-and-dry for our case).

Perhaps we can split having the bento app know the user's on-campus status (and at that point probably affiliation too) into a separate ticket. Down the road we can try to submit something upstream to make this sort of thing easier (as you suggested in slack).

Happy to talk more about this at standup as well.

**Comment by drh-stanford** [comment]
I was under the impression that if we use the X-Forwarded-For header that SearchWorks would do the right IP-based auth (using `request.remote_ip` in its article controller). Is that not the case?

**Comment by mejackreed** [comment]
Sure we could do that @drh-stanford but its a lot of QuickSearch code to overwrite just to get that simple additional header add.
