### ISSUE TITLE
Found results should reflect order of blocks

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#323]
## Current Behavior
![found-results](https://user-images.githubusercontent.com/5402927/89334758-e3258680-d64b-11ea-9805-a6ef5f562d7e.png)

## Desired behavior
Previously, we assumed that Yewno is the last block in results. Given our current searcher order, Yewno should be the 4th item in `Found results`.

We need to deal with Yewno's non-`searcher`-ness in some way so that we can inject it into the middle of this list. 
https://github.com/sul-dlss/sul-bento-app/blob/4d717e83b9f4306b4f78a3e816e6e53cc966fc6c/app/views/layouts/quick_search/_found_types.html.erb#L6-L23

**Comment by jvine** [comment]
... am I misunderstanding this? Yewno _should_ always be the last block?

**Comment by camillevilla** [comment]
@jvine The screenshot is to illustrate current behavior, not desired behavior.
