### ISSUE TITLE
Re-order searchers:  catalog, articles, guides, website, exhibits, yewno

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#327]
per feedback from JV 8/4

**Comment by mejackreed** [comment]
Is it possible to wait on this until we 🚢  libguides? The reason I ask is that we might have some offset columns or more complicated partial logic.

**Comment by jvine** [comment]
Fine w me. I just want to be sure we don't adjust other parts of the UI (e.g. home page, or "found in" results) to match the non-intended order of the blocks.
