### ISSUE TITLE
Add Exhibits to home page

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#336]
@jvine Can you provide an image for the Exhibits card?

![image](https://user-images.githubusercontent.com/5402927/89570583-42fe6780-d7db-11ea-9c4b-5c0eb9db5eab.png)

Related #298 #330

**Comment by jvine** [comment]
![exhibits-bento](https://user-images.githubusercontent.com/6945691/89583917-0852fa00-d7f0-11ea-9a77-8208805a23d9.jpg)
