### ISSUE TITLE
"Found results" list - convert <dl> to <nav>

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#345]
Displaying the count helps to communicate that there are actual results in blocks that are off-screen. 

- Remove the “definition list” layout and change the list to a <nav> element with an aria-label of “Results found in”
- Increase font size of the list elements to match `<h3>` (1.215em)

**Comment by mejackreed** [comment]
nice.. last question @jvine we set h3, and h4 to these. 

```
$h3-font-size: 1.383rem;
$h4-font-size: 1.215rem;
```

Should we use h3 size or the 1.215rem?

**Comment by jvine** [comment]
Oops. This one:

`$h4-font-size: 1.215rem;`
