### ISSUE TITLE
Investigate accessibility of focused searcher indicator (">>")

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#346]
To reproduce:
1. Click on a link in Found Results
2. Window should refocus to selected searcher. ">>" appears next to Searcher title and then disappears after a few seconds.

We'd like to test that behavior in a screenreader and make sure it's not reading that icon as "double arrow"

**Comment by cbeer** [comment]
I'm not hearing "double arrow", but I do hear "Space" (probably from the &nbsp; injected by the JS?).

**Comment by jvine** [comment]
The visible SR caption shows a question mark, but at least it's not reading it. 
![IMG_6528](https://user-images.githubusercontent.com/6945691/90059960-d1219480-dc98-11ea-9d80-3eda95030391.png)

Also just noticed it doesn't play well with a narrower width...
<img width="368" alt="Screen Shot 2020-08-12 at 12 46 34 PM (2)" src="https://user-images.githubusercontent.com/6945691/90060746-0975a280-dc9a-11ea-89e0-07e6b3936f39.png">

Feh.

**Comment by camillevilla** [comment]
Moving to the backlog. We'll have more template flexibility after moving away from quicksearch in #354
