### ISSUE TITLE
"Home" link in libweb breadcrumbs is noisy

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#379]
See accessibility notes from #378

![Bento search results with breadcrumbs from library website](https://user-images.githubusercontent.com/5402927/91511409-71300e00-e894-11ea-9e96-6f13314fb394.png)

Having 3 extra "home" links on the page that don't point to the bento homepage could be noisy or confusing for screen reader users. 

Some ideas for fixes:
1. Add an `aria-label` to "Home" links. Example: "Library website: home" 
2. Disable links for "Home" but render them visually
3. Remove "Home" from breadcrumbs entirely

**Comment by jvine** [comment]
I think #3 makes sense (and have considered it for the Drupal results as well).
