### ISSUE TITLE
Routes issues post quicksearch

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#387]
Rolling back #386 in prod
There's probably more routing and puppet stuff to untangle.

### Stage (pointing at master)
Start search in [bento-stage.stanford.edu](https://bento-stage.stanford.edu/).
On results page, search for another term https://bento-stage.stanford.edu/?q=fish
✅ Successfully returns results

Start search in [library-stage](https://library-stage.stanford.edu/all/). Enter query.
🛑 Query routes to libweb native search: https://library-stage.stanford.edu/medieval

### Stage (pointing at f5864fca747997231c5e4bb12c51412866e3186b)
Start search in [bento-stage.stanford.edu](https://bento-stage.stanford.edu/).
On results page, search for another term https://bento-stage.stanford.edu/?q=fish
✅ Successfully returns results

Start search in [library-stage](https://library-stage.stanford.edu/all/). Enter query.
🚧 Results page loads, but mysterious new param has been added: `op=Search`: https://library-stage.stanford.edu/all/?q=fish&op=Search
🛑 Query routes to libweb native search: https://library-stage.stanford.edu/medieval

### Prod (currently pointing back at pre-global_alerts c7550515e2baf9b600476373e79617e12572a7e3)
we were getting mystery `op=Search` param then too??

**Comment by jkeck** [comment]
A few observations that might be useful in case you jump onto this early in the AM.  the `op=Search` seems to come from the buttons in the search forms on the drupal site. 

<img width="558" alt="Screen Shot 2020-08-31 at 6 25 51 PM" src="https://user-images.githubusercontent.com/96776/91784311-71dbe380-ebb7-11ea-9a3c-bb28db6c47d0.png">

Also, our form_for is routing to the `root_path` which looks like has ended up as `/`.  We might want to piggy-pack on the `quick_search_path` route (or something else) to ensure that the bento's own internal form always routes to `/all`.  

Happy to look at this together tomorrow if we're both available.

**Comment by cbeer** [comment]
(#388)
