### ISSUE TITLE
Allow for bento panels to be loaded asynchronously 

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-bento-app#4]
It appears that the best-bets result is the only one that is loaded asynchronously.  We'll likely want all of our panels to be loaded asynchronously for speed/efficiency purposes.

**Comment by drh-stanford** [comment]
quick_search does have an `xhr_search` endpoint that you can call like so:

http://localhost:3001/xhr_search.json?q=new+zealand&endpoint=article

There is an xhr_search.js file but it's not clear to me how/where it's used -- it appears that it's only used on errors? https://github.com/NCSU-Libraries/quick_search/blob/master/app/assets/javascripts/quick_search/xhr_search.js#L21

**Comment by drh-stanford** [comment]
this is working now.
