### ISSUE TITLE
development environment: why is eager_load needed?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#40]
without eager_load turned on in development, constant loading hangs the app. so development.rb and test.rb both have eager_load turned on.

**Comment by mejackreed** [comment]
This feels suspect to me. I can't put my finger on it entirely.. but this is where I would start to look at this: https://github.com/NCSU-Libraries/quick_search/blob/master/lib/quick_search/engine.rb#L15-L35

**Comment by drh-stanford** [comment]
also see http://guides.rubyonrails.org/engines.html#active-support-on-load-hooks

**Comment by camillevilla** [comment]
We'll be moving away from quicksearch in #354
