### ISSUE TITLE
Add feedback form 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#41]
The current Feedback link is a dummy link. We'll need something similar to SearchWorks. 

![feedback form](https://user-images.githubusercontent.com/5402927/30402951-4e83ecc6-9894-11e7-9106-f39889422355.png)

**Comment by mejackreed** [comment]
@jvine what email should feedback go to?

**Comment by jvine** [comment]
Same one as SearchWorks feedback, to start with.

**Comment by jkeck** [comment]
Will take another look at this when we work on Bento again.

**Comment by camillevilla** [comment]
We currently direct users to the libweb feedback form.
