### ISSUE TITLE
Quotation marks and libweb results 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-bento-app#438]
JV is spending a portion of her retirement searching Bento using quotation marks.  She searched for "instructional design" and got 45 results for the library website, with three results displaying. When you click through to the rest of the library website results, the returned list changes to 2. 

The 2 results actually have "instructional design" in the text.  Creating a search for the term instructional design without quotation marks results in 45 hits, most of which don't have the term "instructional" in the text - let alone "Instructional design". (Most seem to have the term instruction.)

The goal should be to utilize the quotation marks and only get Bento results with the phrase in the quotes, and to get those same results (including the same number) when the user clicks through to the library website results list.

Camille wondered if this might be 

A. an easy to fix on our end - perhaps because Bento encodes quote marks in a funny way before sending them to the libweb API

or

B. if the libweb API is doing something weird and we need to open a case with Chapter Three.

**Comment by saseestone** [comment]
Jira ticket of original report: https://jirasul.stanford.edu/jira/browse/LIBWEBF-24483

**Comment by cbeer** [comment]
I think this is on Chapter 3. We're passing the quotes through just fine. It doesn't seem to matter whether they are URL encoded (as they should be) or not. Here's the URL we're use to get results:

https://library.stanford.edu/bento?keys=%22instructional+design%22

**Comment by saseestone** [comment]
Thanks Chris.  I'll pass it to Ch3.
