### ISSUE TITLE
Update Yewno widget

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-bento-app#505]
Ruth and Carola at Yewno have asked that we update the Yewno widget on Bento. Carola provided information via email, and I've forwarded it to the dlss-access-team list.
 
Carola also provided an API key for the widget: stan_3g4q375f

They are hoping to sunset the widget we are currently using very soon.  I need to give them an estimate on when the work could be completed.

**Comment by ggeisler** [comment]
This has already been communicated elsewhere but for potential future reference purposes, here's a mockup that represents how Sarah, Chris, and I agreed we'd prefer the new version to look in Bento:

<img width="571" alt="SUL-preferred-Yewno-widget" src="https://user-images.githubusercontent.com/101482/176772509-be364e65-6071-4103-9a5f-23c84a3337ee.png">

This configuration:

- Hides the definition(s) below the graph (my view is the definition is more info than our users need in the Bento context)
- Hides the "Here's your search term/definition display toggle" section above the graph (the term is already shown in the graph and when we omit the definition as noted above there is no need for the toggle)

The default configuration looks like this:

<img width="571" alt="Screen Shot 2022-06-30 at 1 32 25 PM" src="https://user-images.githubusercontent.com/101482/176773231-c6ecc4f9-c7cb-49ff-b41f-9e042f8d1df5.png">
