### ISSUE TITLE
add breadcrumbs to search results where available

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#51]
Breadcrumbs are available on the library website and the mockups have them showing

**Comment by jkeck** [comment]
If we can get this from the new API (when it's available), great!  If not, it does not block the release but we should make a feature request to have it added (if not already requested).

**Comment by drh-stanford** [comment]
yes, breadcrumbs are in the [feature request](https://github.com/sul-dlss/sul-bento-app/issues/3#issuecomment-328932018)

**Comment by drh-stanford** [comment]
chapter3 is working on this API still

**Comment by drh-stanford** [comment]
chapter3 has built the JSON API, but it's not deployed to production
