### ISSUE TITLE
Migrate Universal Analytics (UA) to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by corylown** [sul-dlss/sul-bento-app#539]
Universal Analytics (UA) properties will [stop collecting data as of July 1, 2023](https://support.google.com/analytics/answer/11583528?hl=en). The data in the existing UA property will remain available for an unspecified period of time. In order to collect data after July 1, 2023 we will need to create a new GA4 property and add the newer `gtag.js` snippet to the application in order to collect data into the new GA4 property.

Spreadsheet that tracks properties and whether each property is tracking events: https://docs.google.com/spreadsheets/d/1WWt3l-RFqfb_L2j01Y7JBUWJ2OnX0Hi4xLmIW8abNLw/edit?usp=sharing

- [x] [Add a Google Analytics 4 property](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article)
- [x] [Add the Google tag to the application](https://support.google.com/analytics/answer/9304153#zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-google-tag-directly-to-your-web-pages)
- [x] [Set up event tracking as desired](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article). NOTE: _everything_ is an event in GA4 and it automatically collects some events.
- [x]  Set up debug_mode filter (https://support.google.com/analytics/answer/13296662?hl=en)
- [ ] Optionally, download and archive the historical UA data.

NOTE: There is currently a [setting available](https://support.google.com/analytics/answer/11150547) that will send events from `analytics.js` (UA) to GA4 properties. However, Google does not guarantee this will continue to work after July 1, 2023. This is not recommended as a migration path for event tracking.

**Comment by marlo-longley** [comment]
We see references to Google Tag Manager in this code but we don't have access. Who can grant us access to this? We want to remove the code if it is unused (which is what we suspect).

**Comment by hudajkhan** [comment]
The following two pull requests address this issue: 
https://github.com/sul-dlss/sul-bento-app/pull/575
https://github.com/sul-dlss/shared_configs/pull/1945

Based on discussions, we decided to remove the original Google Tag manager code.

**Comment by hudajkhan** [comment]
Interacting with bento-stage shows analytics information in debugmode.  When bento-prod has been updated, I'll check to see that we are not getting debugmode info.

**Comment by hudajkhan** [comment]
I've also add a data filter to exclude developer traffic.

**Comment by marlo-longley** [comment]
Since both PRs are merged and you added the filter, I think we can close!
