### ISSUE TITLE
replace search placeholder text

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#54]
Our homepage searchbar currently displays "Search all the things!", (inherited from `quick_search-generic_theme`) as placeholder text.

Possible solutions:
(1) No placeholder text (shown in mockups)
(2) description text in SearchWorks is "catalog, articles, website, &amp; more in one search"

Opinions, @jvine?

## Current
![searchbar](https://user-images.githubusercontent.com/5402927/30456482-a11bfa7c-9958-11e7-8c91-f4d6bb3f48db.png)

**Comment by jvine** [comment]
Lost in the design drift:   `placeholder="catalog + articles + website + more"`

<img width="433" alt="screen shot 2017-09-14 at 3 21 13 pm" src="https://user-images.githubusercontent.com/6945691/30458442-77b901c2-9960-11e7-823e-2def880f943f.png">
