### ISSUE TITLE
Handle "No results" for each bento search

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#59]
Each bento search should display the following when no results are found:

<img width="390" alt="30459524-1f6fcfae-9966-11e7-991b-eaf9d8f1b434" src="https://user-images.githubusercontent.com/1861171/30494577-9b4f858c-99fd-11e7-9b97-881aed1253d6.png">

**Comment by drh-stanford** [comment]
@jvine the "Try a different search" link currently goes to the service directly (e.g., searchworks.stanford.edu/articles homepage). Is that ok? or do you want it to go to the bento homepage, or where?

**Comment by jvine** [comment]
@drh-stanford I think I like that it goes to the service - let's stay with that for now.
