### ISSUE TITLE
Display Stanford "S" for stanford-only links

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-bento-app#628]
A librarian submitted SearchWorks feedback ([VUF-9483](https://jirasul.stanford.edu/jira/browse/VUF-9483)) asking that we include the "Stanford S" in catalog results when the search results include stanford-only links. 

Example Bento search: https://library.stanford.edu/all?q=U.K.+parliamentary+papers
-Bento catalog results: 
<img width="435" alt="image" src="https://github.com/sul-dlss/sul-bento-app/assets/14897546/dfda2916-5e4a-4414-9765-fea44384aeec">
-Clicking through to see the SearchWorks catalog results shows the Stanford S: 
<img width="638" alt="image" src="https://github.com/sul-dlss/sul-bento-app/assets/14897546/ded8c612-b924-4ac4-a698-abe1589aca3f">

Is this possible? 

Noting that we should also look into doing the same for Articles+

**Comment by jcoyne** [comment]
Is there any way to know the link is "stanford only" from looking at the metadata?
