### ISSUE TITLE
Stylin' details for bento (based on -stage 2:12p Friday)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-bento-app#68]
Not sure how much of this is currently WIP in #15

- [ ] please use the btn-primary styling from SearchWorks for the see-all-results links. The current link doesn't stand out enough. Note: it was intentional design to have the "see-all" button up at the top next to the header. If it's not possible to move it within the time constraints, okay; regardless, it needs to be much more visible. 

- [x] base font size should be 15px. Current 16 so it doesn't match either website nor SW.

- [x] reduce vertical spacing between the elements of each result. Currently individual results are not holding together visually.

- [ ] add the "Full text" label styling (see SW) to the full text links in the Articles+ section.

**Comment by mejackreed** [comment]
First item really has a pre-req of #66

**Comment by drh-stanford** [comment]
Also the "More search tools" heading is off now:

![screen shot 2017-09-20 at 10 08 26 am](https://user-images.githubusercontent.com/1861171/30657233-b4bfabc2-9deb-11e7-8d7e-cd2b8f908879.png)
