### ISSUE TITLE
Create and configure google_analytics_tracking_id

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#85]
We need to create and configure a `google_analytics_tracking_id` in quick_search_config.yml for production.

**Comment by drh-stanford** [comment]
Does someone know how to go about creating a new Google analytics id?

**Comment by jkeck** [comment]
@drh-stanford I just added your account (via your Stanford email) to our analytics.  You have admin rights so you should be able to add a new property.

Let me know if you're running into any trouble.
