### ISSUE TITLE
Display facet data for bento results

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-bento-app#9]
Allow the display of facet data (from a particular facet for each source) in the bento search results interface.

**Comment by jvine** [comment]
Catalog:  Resource type 
Articles: Source type 
Website:  Type (which refers to content type)

**Comment by camillevilla** [comment]
![article results](https://user-images.githubusercontent.com/5402927/30352320-2a006b56-97d4-11e7-9188-c21cd8877755.png)
![catalog results](https://user-images.githubusercontent.com/5402927/30352319-29fb8da2-97d4-11e7-9bf2-6fdde0e3893f.png)
![library website results](https://user-images.githubusercontent.com/5402927/30352318-29f38d78-97d4-11e7-89cd-3f07dca65fb6.png)
